local wezterm = require('wezterm')
local platform = require('utils.platform')()
local act = wezterm.action

local mod = {}

if platform.is_mac then
   mod.SUPER = 'SUPER'
   mod.SUPER_REV = 'SUPER|CTRL'
elseif platform.is_win or platform.is_linux then
   mod.SUPER = 'ALT' -- to not conflict with Windows key shortcuts
   mod.SUPER_REV = 'ALT|CTRL'
end

-- stylua: ignore
local keys = {
   -- misc/useful --
   { key = 'F1', mods = 'NONE', action = 'ActivateCopyMode' },
   { key = 'F2', mods = 'NONE', action = act.ActivateCommandPalette },
   { key = 'F3', mods = 'NONE', action = act.ShowLauncher },
   { key = 'F4', mods = 'NONE', action = act.ShowLauncherArgs({ flags = 'FUZZY|TABS' }) },
   {
      key = 'F5',
      mods = 'NONE',
      action = act.ShowLauncherArgs({ flags = 'FUZZY|WORKSPACES' }),
   },
   { key = 'F11', mods = 'NONE',    action = act.ToggleFullScreen },
   { key = 'F12', mods = 'NONE',    action = act.ShowDebugOverlay },
   { key = 'f',   mods = mod.SUPER, action = act.Search({ CaseInSensitiveString = '' }) },
   {
      key = 'u',
      mods = mod.SUPER,
      action = wezterm.action.QuickSelectArgs({
         label = 'open url',
         patterns = {
            '\\((https?://\\S+)\\)',
            '\\[(https?://\\S+)\\]',
            '\\{(https?://\\S+)\\}',
            '<(https?://\\S+)>',
            '\\bhttps?://\\S+[)/a-zA-Z0-9-]+'
         },
         action = wezterm.action_callback(function(window, pane)
            local url = window:get_selection_text_for_pane(pane)
            wezterm.log_info('opening: ' .. url)
            wezterm.open_with(url)
         end),
      }),
   },

   -- cursor movement --
   { key = 'LeftArrow',  mods = mod.SUPER,     action = act.SendString '\x1bOH' },
   { key = 'RightArrow', mods = mod.SUPER,     action = act.SendString '\x1bOF' },
   { key = 'Backspace',  mods = mod.SUPER,     action = act.SendString '\x15' },

   -- copy/paste --
   { key = 'c',          mods = mod.SUPER,  action = act.CopyTo('Clipboard') },
   { key = 'v',          mods = mod.SUPER,  action = act.PasteFrom('Clipboard') },

   -- tabs --
   -- tabs: spawn+close
   { key = 't',          mods = mod.SUPER,     action = act.SpawnTab('DefaultDomain') },
   { key = 't',          mods = mod.SUPER_REV, action = act.SpawnTab({ DomainName = 'WSL:Ubuntu' }) },
   { key = 'w',          mods = mod.SUPER_REV, action = act.CloseCurrentTab({ confirm = false }) },

   -- tabs: navigation
   { key = '[',          mods = mod.SUPER,     action = act.ActivateTabRelative(-1) },
   { key = ']',          mods = mod.SUPER,     action = act.ActivateTabRelative(1) },
   { key = '[',          mods = mod.SUPER_REV, action = act.MoveTabRelative(-1) },
   { key = ']',          mods = mod.SUPER_REV, action = act.MoveTabRelative(1) },

   -- window --
   -- spawn windows
   { key = 'n',          mods = mod.SUPER,     action = act.SpawnWindow },

   -- quit wezterm
   { key = 'q', mods = 'CMD', action = wezterm.action.QuitApplication },

   -- background controls --
   --[==[
   {
      key = [[/]],
      mods = mod.SUPER,
      action = wezterm.action_callback(function(window, _pane)
         backdrops:random(window)
      end),
   },
   {
      key = [[,]],
      mods = mod.SUPER,
      action = wezterm.action_callback(function(window, _pane)
         backdrops:cycle_back(window)
      end),
   },
   {
      key = [[.]],
      mods = mod.SUPER,
      action = wezterm.action_callback(function(window, _pane)
         backdrops:cycle_forward(window)
      end),
   },
   {
      key = [[/]],
      mods = mod.SUPER_REV,
      action = act.InputSelector({
         title = 'Select Background',
         choices = backdrops:choices(),
         fuzzy = true,
         fuzzy_description = 'Select Background: ',
         action = wezterm.action_callback(function(window, _pane, idx)
            ---@diagnostic disable-next-line: param-type-mismatch
            backdrops:set_img(window, tonumber(idx))
         end),
      }),
   },
   --]==]

   -- panes --
   -- panes: split panes
   {
      key = [[\]],
      mods = mod.SUPER,
      action = act.SplitVertical({ domain = 'CurrentPaneDomain' }),
   },
   {
      key = [[\]],
      mods = mod.SUPER_REV,
      action = act.SplitHorizontal({ domain = 'CurrentPaneDomain' }),
   },

   -- panes: zoom+close pane
   { key = 'Enter', mods = mod.SUPER,     action = act.TogglePaneZoomState },
   { key = 'w',     mods = mod.SUPER,     action = act.CloseCurrentPane({ confirm = false }) },

   -- panes: navigation
   { key = 'k',     mods = mod.SUPER_REV, action = act.ActivatePaneDirection('Up') },
   { key = 'j',     mods = mod.SUPER_REV, action = act.ActivatePaneDirection('Down') },
   { key = 'h',     mods = mod.SUPER_REV, action = act.ActivatePaneDirection('Left') },
   { key = 'l',     mods = mod.SUPER_REV, action = act.ActivatePaneDirection('Right') },
   {
      key = 'p',
      mods = mod.SUPER_REV,
      action = act.PaneSelect({ alphabet = '1234567890', mode = 'SwapWithActiveKeepFocus' }),
   },

   -- windows: navigation
   { key = '1',     mods = mod.SUPER, action = act.ActivateTab(0) },
   { key = '2',     mods = mod.SUPER, action = act.ActivateTab(1) },
   { key = '3',     mods = mod.SUPER, action = act.ActivateTab(2) },
   { key = '4',     mods = mod.SUPER, action = act.ActivateTab(3) },
   { key = '5',     mods = mod.SUPER, action = act.ActivateTab(4) },
   { key = '6',     mods = mod.SUPER, action = act.ActivateTab(5) },
   { key = '7',     mods = mod.SUPER, action = act.ActivateTab(6) },
   { key = '8',     mods = mod.SUPER, action = act.ActivateTab(7) },
   { key = '9',     mods = mod.SUPER, action = act.ActivateTab(-1) },

   -- key-tables --
   -- resizes fonts
   {
      key = 'f',
      mods = 'LEADER',
      action = act.ActivateKeyTable({
         name = 'resize_font',
         one_shot = false,
         timemout_miliseconds = 1000,
      }),
   },
   -- resize panes
   {
      key = 'p',
      mods = 'LEADER',
      action = act.ActivateKeyTable({
         name = 'resize_pane',
         one_shot = false,
         timemout_miliseconds = 1000,
      }),
   },

   -- wezterm keys
  {key = "`", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2a\x62\x1f"}},
  {key = "~", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x2a\x63\x1f"}},
  {key = "`", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2a\x66\x1f"}},
  {key = "~", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2a\x67\x1f"}},
  {key = "1", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2b\x42\x1f"}},
  {key = "!", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x2b\x43\x1f"}},
  {key = "1", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2b\x46\x1f"}},
  {key = "!", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2b\x47\x1f"}},
  {key = "2", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2c\x22\x1f"}},
  {key = "@", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x2c\x23\x1f"}},
  {key = "2", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2c\x26\x1f"}},
  {key = "@", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2c\x27\x1f"}},
  {key = "3", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2c\x62\x1f"}},
  {key = "#", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x2c\x63\x1f"}},
  {key = "3", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2c\x66\x1f"}},
  {key = "#", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2c\x67\x1f"}},
  {key = "4", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2d\x42\x1f"}},
  {key = "$", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x2d\x43\x1f"}},
  {key = "4", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2d\x46\x1f"}},
  {key = "$", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2d\x47\x1f"}},
  {key = "5", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2e\x22\x1f"}},
  {key = "%", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x2e\x23\x1f"}},
  {key = "5", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2e\x26\x1f"}},
  {key = "%", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2e\x27\x1f"}},
  {key = "6", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2e\x62\x1f"}},
  {key = "^", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x2e\x63\x1f"}},
  {key = "6", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2e\x66\x1f"}},
  {key = "^", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2e\x67\x1f"}},
  {key = "7", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x2f\x42\x1f"}},
  {key = "&", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x2f\x43\x1f"}},
  {key = "7", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2f\x46\x1f"}},
  {key = "&", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x2f\x47\x1f"}},
  {key = "8", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x30\x22\x1f"}},
  {key = "*", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x30\x23\x1f"}},
  {key = "8", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x30\x26\x1f"}},
  {key = "*", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x30\x27\x1f"}},
  {key = "9", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x30\x62\x1f"}},
  {key = "(", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x30\x63\x1f"}},
  {key = "9", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x30\x66\x1f"}},
  {key = "(", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x30\x67\x1f"}},
  {key = "0", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x31\x42\x1f"}},
  {key = ")", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x31\x43\x1f"}},
  {key = "0", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x31\x46\x1f"}},
  {key = ")", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x31\x47\x1f"}},
  {key = "-", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x32\x22\x1f"}},
  {key = "_", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x32\x23\x1f"}},
  {key = "-", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x32\x26\x1f"}},
  {key = "_", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x32\x27\x1f"}},
  {key = "=", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x32\x62\x1f"}},
  {key = "+", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x32\x63\x1f"}},
  {key = "=", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x32\x66\x1f"}},
  {key = "+", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x32\x67\x1f"}},
  {key = "Backspace", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x33\x41\x1f"}},
  {key = "Backspace", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x33\x42\x1f"}},
  {key = "Backspace", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x33\x43\x1f"}},
  {key = "Backspace", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x33\x45\x1f"}},
  {key = "Backspace", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x33\x46\x1f"}},
  {key = "Backspace", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x33\x47\x1f"}},
  {key = "Tab", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x34\x22\x1f"}},
  {key = "Tab", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x34\x23\x1f"}},
  {key = "Tab", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x34\x26\x1f"}},
  {key = "Tab", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x34\x27\x1f"}},
  {key = "Q", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x34\x63\x1f"}},
  {key = "Q", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x34\x67\x1f"}},
  {key = "W", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x35\x43\x1f"}},
  {key = "W", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x35\x47\x1f"}},
  {key = "E", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x36\x23\x1f"}},
  {key = "E", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x36\x27\x1f"}},
  {key = "R", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x36\x63\x1f"}},
  {key = "R", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x36\x67\x1f"}},
  {key = "T", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x37\x43\x1f"}},
  {key = "T", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x37\x47\x1f"}},
  {key = "Y", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x38\x23\x1f"}},
  {key = "Y", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x38\x27\x1f"}},
  {key = "U", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x38\x63\x1f"}},
  {key = "U", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x38\x67\x1f"}},
  {key = "I", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x39\x43\x1f"}},
  {key = "I", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x39\x47\x1f"}},
  {key = "O", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x3a\x23\x1f"}},
  {key = "O", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3a\x27\x1f"}},
  {key = "P", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x3a\x63\x1f"}},
  {key = "P", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3a\x67\x1f"}},
  {key = "[", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x3b\x42\x1f"}},
  {key = "{", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x3b\x43\x1f"}},
  {key = "[", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3b\x46\x1f"}},
  {key = "{", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3b\x47\x1f"}},
  {key = "]", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x3c\x22\x1f"}},
  {key = "}", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x3c\x23\x1f"}},
  {key = "]", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3c\x26\x1f"}},
  {key = "}", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3c\x27\x1f"}},
  {key = "Enter", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x3c\x61\x1f"}},
  {key = "Enter", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x3c\x62\x1f"}},
  {key = "Enter", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x3c\x63\x1f"}},
  {key = "Enter", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x3c\x65\x1f"}},
  {key = "Enter", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3c\x66\x1f"}},
  {key = "Enter", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3c\x67\x1f"}},
  {key = "A", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x3e\x23\x1f"}},
  {key = "A", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3e\x27\x1f"}},
  {key = "S", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x3e\x63\x1f"}},
  {key = "S", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3e\x67\x1f"}},
  {key = "D", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x3f\x43\x1f"}},
  {key = "D", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x3f\x47\x1f"}},
  {key = "F", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x40\x23\x1f"}},
  {key = "F", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x40\x27\x1f"}},
  {key = "G", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x40\x63\x1f"}},
  {key = "G", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x40\x66\x1f"}},
  {key = "G", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x40\x67\x1f"}},
  {key = "H", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x41\x43\x1f"}},
  {key = "H", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x41\x47\x1f"}},
  {key = "J", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x42\x23\x1f"}},
  {key = "J", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x42\x27\x1f"}},
  {key = "K", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x42\x63\x1f"}},
  {key = "K", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x42\x67\x1f"}},
  {key = "L", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x43\x43\x1f"}},
  {key = "L", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x43\x47\x1f"}},
  {key = ";", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x44\x22\x1f"}},
  {key = ":", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x44\x23\x1f"}},
  {key = ";", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x44\x26\x1f"}},
  {key = ":", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x44\x27\x1f"}},
  {key = "'", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x44\x62\x1f"}},
  {key = "\"", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x44\x63\x1f"}},
  {key = "'", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x44\x66\x1f"}},
  {key = "\"", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x44\x67\x1f"}},
  {key = "\\", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x46\x22\x1f"}},
  {key = "|", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x46\x23\x1f"}},
  {key = "\\", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x46\x26\x1f"}},
  {key = "|", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x46\x27\x1f"}},
  {key = "Z", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x46\x63\x1f"}},
  {key = "Z", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x46\x67\x1f"}},
  {key = "X", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x47\x43\x1f"}},
  {key = "X", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x47\x47\x1f"}},
  {key = "C", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x48\x23\x1f"}},
  {key = "C", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x48\x27\x1f"}},
  {key = "V", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x48\x63\x1f"}},
  {key = "V", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x48\x67\x1f"}},
  {key = "B", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x49\x43\x1f"}},
  {key = "B", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x49\x47\x1f"}},
  {key = "N", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x4a\x23\x1f"}},
  {key = "N", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4a\x27\x1f"}},
  {key = "M", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x4a\x63\x1f"}},
  {key = "M", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4a\x67\x1f"}},
  {key = ",", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x4b\x42\x1f"}},
  {key = "<", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x4b\x43\x1f"}},
  {key = ",", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4b\x46\x1f"}},
  {key = "<", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4b\x47\x1f"}},
  {key = ".", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x4c\x22\x1f"}},
  {key = ">", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x4c\x23\x1f"}},
  {key = ".", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4c\x26\x1f"}},
  {key = ">", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4c\x27\x1f"}},
  {key = "/", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x4c\x62\x1f"}},
  {key = "?", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x4c\x63\x1f"}},
  {key = "/", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4c\x66\x1f"}},
  {key = "?", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x4c\x67\x1f"}},
  {key = "Space", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x50\x22\x1f"}},
  {key = "Space", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x50\x23\x1f"}},
  {key = "Space", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x50\x26\x1f"}},
  {key = "Space", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x50\x27\x1f"}},
  {key = "Applications", mods = "", action = wezterm.action{SendString="\x1b\x1f\x52\x20\x1f"}},
  {key = "Applications", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x52\x21\x1f"}},
  {key = "Applications", mods = "CTRL", action = wezterm.action{SendString="\x1b\x1f\x52\x22\x1f"}},
  {key = "Applications", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x52\x23\x1f"}},
  {key = "Applications", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x52\x24\x1f"}},
  {key = "Applications", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x52\x25\x1f"}},
  {key = "Applications", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x52\x26\x1f"}},
  {key = "Applications", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x52\x27\x1f"}},
  {key = "UpArrow", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x53\x43\x1f"}},
  {key = "UpArrow", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x53\x44\x1f"}},
  {key = "UpArrow", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x53\x45\x1f"}},
  {key = "UpArrow", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x53\x46\x1f"}},
  {key = "UpArrow", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x53\x47\x1f"}},
  {key = "DownArrow", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x54\x23\x1f"}},
  {key = "DownArrow", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x24\x1f"}},
  {key = "DownArrow", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x25\x1f"}},
  {key = "DownArrow", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x26\x1f"}},
  {key = "DownArrow", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x27\x1f"}},
  {key = "LeftArrow", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x54\x63\x1f"}},
  {key = "LeftArrow", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x64\x1f"}},
  {key = "LeftArrow", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x65\x1f"}},
  {key = "LeftArrow", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x66\x1f"}},
  {key = "LeftArrow", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x54\x67\x1f"}},
  {key = "RightArrow", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x55\x43\x1f"}},
  {key = "RightArrow", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x55\x44\x1f"}},
  {key = "RightArrow", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x55\x45\x1f"}},
  {key = "RightArrow", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x55\x46\x1f"}},
  {key = "RightArrow", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x55\x47\x1f"}},
  {key = "Home", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x57\x43\x1f"}},
  {key = "Home", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x57\x44\x1f"}},
  {key = "Home", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x57\x45\x1f"}},
  {key = "Home", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x57\x46\x1f"}},
  {key = "Home", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x57\x47\x1f"}},
  {key = "End", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x58\x23\x1f"}},
  {key = "End", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x24\x1f"}},
  {key = "End", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x25\x1f"}},
  {key = "End", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x26\x1f"}},
  {key = "End", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x27\x1f"}},
  {key = "PageUp", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x58\x61\x1f"}},
  {key = "PageUp", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x58\x63\x1f"}},
  {key = "PageUp", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x64\x1f"}},
  {key = "PageUp", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x65\x1f"}},
  {key = "PageUp", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x66\x1f"}},
  {key = "PageUp", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x58\x67\x1f"}},
  {key = "PageDown", mods = "SHIFT", action = wezterm.action{SendString="\x1b\x1f\x59\x41\x1f"}},
  {key = "PageDown", mods = "SHIFT|CTRL", action = wezterm.action{SendString="\x1b\x1f\x59\x43\x1f"}},
  {key = "PageDown", mods = "ALT", action = wezterm.action{SendString="\x1b\x1f\x59\x44\x1f"}},
  {key = "PageDown", mods = "SHIFT|ALT", action = wezterm.action{SendString="\x1b\x1f\x59\x45\x1f"}},
  {key = "PageDown", mods = "CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x59\x46\x1f"}},
  {key = "PageDown", mods = "SHIFT|CTRL|ALT", action = wezterm.action{SendString="\x1b\x1f\x59\x47\x1f"}},
}

-- stylua: ignore
local key_tables = {
   resize_font = {
      { key = 'k',      action = act.IncreaseFontSize },
      { key = 'j',      action = act.DecreaseFontSize },
      { key = 'r',      action = act.ResetFontSize },
      { key = 'Escape', action = 'PopKeyTable' },
      { key = 'q',      action = 'PopKeyTable' },
   },
   resize_pane = {
      { key = 'k',      action = act.AdjustPaneSize({ 'Up', 1 }) },
      { key = 'j',      action = act.AdjustPaneSize({ 'Down', 1 }) },
      { key = 'h',      action = act.AdjustPaneSize({ 'Left', 1 }) },
      { key = 'l',      action = act.AdjustPaneSize({ 'Right', 1 }) },
      { key = 'Escape', action = 'PopKeyTable' },
      { key = 'q',      action = 'PopKeyTable' },
      {key=" ",mods="CTRL|ALT",action=wezterm.action{SendString="\x1b[====\x20"}},
      {key="g",mods="CTRL|ALT",action=wezterm.action{SendString="\x1b[====\x67"}},
      {key=" ",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x20"}},
      {key=" ",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x20"}},
      {key="0",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x30"}},
      {key="1",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x31"}},
      {key="2",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x32"}},
      {key="3",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x33"}},
      {key="4",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x34"}},
      {key="5",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x35"}},
      {key="6",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x36"}},
      {key="7",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x37"}},
      {key="8",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x38"}},
      {key="9",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x39"}},
      {key="a",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x61"}},
      {key="b",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x62"}},
      {key="c",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x63"}},
      {key="d",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x64"}},
      {key="e",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x65"}},
      {key="f",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x66"}},
      {key="g",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x67"}},
      {key="h",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x68"}},
      {key="i",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x69"}},
      {key="j",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x6a"}},
      {key="k",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x6b"}},
      {key="l",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x6c"}},
      {key="m",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x6d"}},
      {key="n",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x6e"}},
      {key="o",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x6f"}},
      {key="p",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x70"}},
      {key="q",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x71"}},
      {key="r",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x72"}},
      {key="s",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x73"}},
      {key="t",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x74"}},
      {key="u",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x75"}},
      {key="v",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x76"}},
      {key="w",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x77"}},
      {key="x",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x78"}},
      {key="y",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x79"}},
      {key="z",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x7a"}},
      {key="`",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x60"}},
      {key="-",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x2d"}},
      {key="=",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x3d"}},
      {key="[",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x5b"}},
      {key="]",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x5d"}},
      {key="\\",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x5c"}},
      {key=";",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x3b"}},
      {key="'",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x27"}},
      {key=",",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x2c"}},
      {key=".",mods="SUPER",action=wezterm.action{SendString="\x18\x40\x68\x2e"}},
      {key="/",mods="SUPER",action=wezterm.action{SendString="\x18\x2f"}},
      {key="~",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x7e"}},
      {key="_",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x5f"}},
      {key="+",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x2b"}},
      {key="{",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x7b"}},
      {key="}",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x7d"}},
      {key="|",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x7c"}},
      {key=":",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x3a"}},
      {key="\"",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x22"}},
      {key="<",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x3c"}},
      {key=">",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x3e"}},
      {key="?",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x3f"}},
      {key=")",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x29"}},
      {key="!",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x21"}},
      {key="@",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x40"}},
      {key="#",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x23"}},
      {key="$",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x24"}},
      {key="%",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x25"}},
      {key="^",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x5e"}},
      {key="&",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x26"}},
      {key="*",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x2a"}},
      {key="(",mods="SUPER",action=wezterm.action{SendString="\x1b[======\x28"}},
      {key=" ",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x20"}},
      {key="A",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x41"}},
      {key="B",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x42"}},
      {key="C",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x43"}},
      {key="D",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x44"}},
      {key="E",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x45"}},
      {key="F",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x46"}},
      {key="G",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x47"}},
      {key="H",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x48"}},
      {key="I",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x49"}},
      {key="J",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x4a"}},
      {key="K",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x4b"}},
      {key="L",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x4c"}},
      {key="M",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x4d"}},
      {key="N",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x4e"}},
      {key="O",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x4f"}},
      {key="P",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x50"}},
      {key="Q",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x51"}},
      {key="R",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x52"}},
      {key="S",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x53"}},
      {key="T",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x54"}},
      {key="U",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x55"}},
      {key="V",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x56"}},
      {key="W",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x57"}},
      {key="X",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x58"}},
      {key="Y",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x59"}},
      {key="Z",mods="SUPER|SHIFT",action=wezterm.action{SendString="\x1b[======\x5a"}},
      {key="1",mods="CTRL",action=wezterm.action{SendString="\x18\x40\x63\x31"}},
      {key="2",mods="CTRL",action=wezterm.action{SendString="\x18\x40\x63\x32"}},
      {key="3",mods="CTRL",action=wezterm.action{SendString="\x18\x40\x63\x33"}},
      {key="4",mods="CTRL",action=wezterm.action{SendString="\x18\x40\x63\x34"}},
      {key="5",mods="CTRL",action=wezterm.action{SendString="\x18\x40\x63\x35"}},
      {key="6",mods="CTRL",action=wezterm.action{SendString="\x18\x40\x63\x36"}},
      {key="7",mods="CTRL",action=wezterm.action{SendString="\x18\x40\x63\x37"}},
      {key="8",mods="CTRL",action=wezterm.action{SendString="\x18\x40\x63\x38"}},
      {key="9",mods="CTRL",action=wezterm.action{SendString="\x18\x40\x63\x39"}},
      {key="A",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x41"}},
      {key="B",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x42"}},
      {key="C",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x43"}},
      {key="D",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x44"}},
      {key="E",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x45"}},
      {key="F",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x46"}},
      {key="G",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x47"}},
      {key="H",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x48"}},
      {key="I",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x49"}},
      {key="J",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x4a"}},
      {key="K",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x4b"}},
      {key="L",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x4c"}},
      {key="M",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x4d"}},
      {key="N",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x4e"}},
      {key="O",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x4f"}},
      {key="P",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x50"}},
      {key="Q",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x51"}},
      {key="R",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x52"}},
      {key="S",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x53"}},
      {key="T",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x54"}},
      {key="U",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x55"}},
      {key="V",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x56"}},
      {key="W",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x57"}},
      {key="X",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x58"}},
      {key="Y",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x59"}},
      {key="Z",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x5a"}},
      {key=" ",mods="CTRL|SHIFT",action=wezterm.action{SendString="\x1b[=\x20"}},
      {key="A",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x41"}},
      {key="B",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x42"}},
      {key="C",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x43"}},
      {key="D",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x44"}},
      {key="E",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x45"}},
      {key="F",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x46"}},
      {key="G",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x47"}},
      {key="H",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x48"}},
      {key="I",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x49"}},
      {key="J",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x4a"}},
      {key="K",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x4b"}},
      {key="L",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x4c"}},
      {key="M",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x4d"}},
      {key="N",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x4e"}},
      {key="O",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x4f"}},
      {key="P",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x50"}},
      {key="Q",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x51"}},
      {key="R",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x52"}},
      {key="S",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x53"}},
      {key="T",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x54"}},
      {key="U",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x55"}},
      {key="V",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x56"}},
      {key="W",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x57"}},
      {key="X",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x58"}},
      {key="Y",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x59"}},
      {key="Z",mods="CTRL|SHIFT|ALT",action=wezterm.action{SendString="\x1b[==\x5a"}},
      {key=" ",mods="SHIFT",action=wezterm.action{SendString="\x18\x40\x53\x20"}},
      {key="\\",mods="CTRL|ALT",action=wezterm.action{SplitHorizontal={domain="CurrentPaneDomain"}}},
      {key="h",mods="CTRL|ALT|SUPER",action=wezterm.action{ActivatePaneDirection="Left"}},
      {key="j",mods="CTRL|ALT|SUPER",action=wezterm.action{ActivatePaneDirection="Down"}},
      {key="k",mods="CTRL|ALT|SUPER",action=wezterm.action{ActivatePaneDirection="Up"}},
      {key="l",mods="CTRL|ALT|SUPER",action=wezterm.action{ActivatePaneDirection="Right"}},
   },
}

local mouse_bindings = {
   -- Ctrl-click will open the link under the mouse cursor
   {
      event = { Up = { streak = 1, button = 'Left' } },
      mods = 'CTRL',
      action = act.OpenLinkAtMouseCursor,
   },
}

return {
   disable_default_key_bindings = true,
   enable_kitty_keyboard = true,
   leader = { key = 'Space', mods = mod.SUPER_REV },
   keys = keys,
   key_tables = key_tables,
   mouse_bindings = mouse_bindings,
}
